Postgres: replace ENUM DOMAINs with TYPEs
Before:

idb=# select * from icingadb_instance where responsible = 'y';
ERROR:  operator does not exist: boolenum = unknown
LINE 1: select * from icingadb_instance where responsible = 'y';
                                                          ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
idb=#

refs #136